<?php

/**
 * @file openid_bakery.module
 */

/**
 * Implementation of hook_form_alter : adds Bakery master redirect link.
 */
function openid_bakery_form_alter(&$form, $form_state, $form_id) {
  // Only modify the login links on Bakery slave sites without OpenID enabled.
  if (module_exists('bakery') && !module_exists('openid') && in_array($form_id, array('user_login_block', 'user_login'))) {
    // Get Bakery master.
    $master = variable_get('bakery_master', 'http://drupal.org/');
    $items = array();
    // @todo would be great to have OpenID element visible.
    $items[] = array(
      'data' => l(t('Log in using OpenID'), $master . 'user', array('html' => TRUE)),
    );
    
    $form['openid_links'] = array(
      '#value' => theme('item_list', $items),
      '#weight' => 1,
    );

    $form['links']['#weight'] = 2;
  }
}